"""Initial migration

Revision ID: 291ce8b0f1d8
Revises: 
Create Date: 2025-07-15 11:37:01.622658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291ce8b0f1d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('salutation', sa.Enum('Mr.', 'Ms.', 'Others'), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other'), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('place_of_birth', sa.String(length=150), nullable=True),
    sa.Column('height', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('no_of_dependents', sa.Integer(), nullable=True),
    sa.Column('marital_status', sa.Enum('Single', 'Married', 'Divorced', 'Widowed', 'Separated', 'Other'), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('education', sa.String(length=150), nullable=True),
    sa.Column('spouse_name', sa.String(length=150), nullable=True),
    sa.Column('spouse_birthdate', sa.Date(), nullable=True),
    sa.Column('work', sa.String(length=150), nullable=True),
    sa.Column('monthly_income', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('address_information',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('barangay', sa.String(length=100), nullable=True),
    sa.Column('city_municipality', sa.String(length=150), nullable=True),
    sa.Column('province', sa.String(length=150), nullable=True),
    sa.Column('region', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_insured',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('business', 'sales', 'household'), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'semi_monthly', 'monthly'), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('business', 'sales', 'household'), nullable=True),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'semi_monthly', 'monthly'), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('income')
    op.drop_table('expense')
    op.drop_table('co_insured')
    op.drop_table('beneficiaries')
    op.drop_table('address_information')
    op.drop_table('client')
    # ### end Alembic commands ###
