"""existing + cif

Revision ID: 47dc013f144e
Revises: 6a44a9cccce1
Create Date: 2025-08-27 14:29:08.056231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47dc013f144e'
down_revision = '6a44a9cccce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('existing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('CIF_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('CIF_number')
        batch_op.drop_column('existing')

    # ### end Alembic commands ###
