"""demo

Revision ID: 621ea29d1c36
Revises: e3ca453b46ff
Create Date: 2025-08-26 20:24:00.577404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621ea29d1c36'
down_revision = 'e3ca453b46ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_flow_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('weekly_cash_flow', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('cash_flow_category', sa.Enum('Below180', 'Exactly180', 'Above180', 'SufficientMatches', 'ExceedsInstallment', name='cashflowcategoryenum'), nullable=False),
    sa.Column('desired_weekly_installment', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('center_collection_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('collection_status', sa.Enum('WeeklyPaymentsNotCompleted', 'PaymentsIncompleteDueDateCompletedWithinWeek', 'PaymentsCompletedMoreThan2hrsLateAfterADFollowup', 'PaymentsCompletedOnTime', 'PaymentsCompletedWithinSchedulePromptly', name='collectionrecordenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('center_status_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('member_count', sa.Enum('FiveToTenMembers', 'ElevenToFifteenMembers', 'TwentySixOrMoreMembers', 'SixteenToTwentyMembers', 'TwentyOneToTwentyFiveMembers', name='centermembersenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('co_insured',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('relationship', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('Business', 'Sales', 'Household', name='incomeexpensetypeenum'), nullable=True),
    sa.Column('frequency', sa.Enum('Daily', 'Weekly', 'SemiMonthly', 'Monthly', name='frequencyenum'), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('family_and_toilet_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('family_status', sa.Enum('SeparatedNewPartner', 'WidowedSeparatedAlone', 'Single', 'LivingWithPartner', 'LegallyMarried', 'Other', name='familystatusenum'), nullable=False),
    sa.Column('family_status_custom', sa.String(length=255), nullable=True),
    sa.Column('toilet_status', sa.Enum('NoPersonalToilet', 'ToiletOutsideHome', 'ToiletInsideNoWater', 'ToiletInsideWithWater', 'ToiletInsideWaterTiled', 'Other', name='toiletstatusenum'), nullable=False),
    sa.Column('toilet_status_custom', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('Business', 'Sales', 'Household', name='incomeexpensetypeenum'), nullable=True),
    sa.Column('frequency', sa.Enum('Daily', 'Weekly', 'SemiMonthly', 'Monthly', name='frequencyenum'), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lending_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('group_participation', sa.Enum('MemberOfMoreThan4Groups', 'NoExperienceWithLoanGroup', 'MemberOf3To4Groups', 'SpouseMemberOfAnotherGroup', 'MemberOf1To2Groups', name='lendinggroupsenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('attendance_frequency', sa.Enum('AttendedOnceIn6Months', 'AttendedTwiceIn6Months', 'Attended3TimesIn6Months', 'Attended4TimesIn6Months', 'Attended5OrMoreTimesIn6Months', name='meetingattendanceenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_repayment_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('PensionSubsidy', 'SidelineHustle', 'LandFarming', 'SpouseChildIncome', 'Remittances', 'Other', name='otherrepaymentsourceenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pastdue_ratio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('ratio_category', sa.Enum('FourPercentOrHigher', 'ThreePercent', 'TwoPercent', 'OnePercent', 'ZeroPercentNoPastDue', name='pastdueratioenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('payment_status', sa.Enum('NoWeeklyPaymentsNotCoveredByOthers', 'OneToTwoRedMarksInPassbook', 'CoveredByCenterWithinTime', 'WeeklyContributionsUpToDate', 'PersonallyPaysOnTime', name='paymenthistoryenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('primary_repayment_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.Enum('Agriculture', 'InformalBusiness', 'StableOccupation', 'PermanentStall', 'RegisteredBusiness', 'Other', name='primaryrepaymentsourceenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('program_benefits_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('benefits_name', sa.Enum('GYRT_LIFE_INSURANCE', 'CGL_LOAN_INSURANCE', 'BYA_MEDICAL_ASSISTANCE', 'BYA_EDUCATIONAL_ASSISTANCE', 'NONE', name='programbenefitsenum'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('length_of_stay', sa.Enum('OneToTwoYears', 'ThreeToFiveYears', 'MoreThanFiveYears', 'SpouseSinceChildhood', 'ApplicantSinceChildhood', 'Other', name='lengthofstayenum'), nullable=False),
    sa.Column('length_of_stay_custom', sa.String(length=255), nullable=True),
    sa.Column('ownership_type', sa.Enum('Renting', 'Squatter', 'Tenant', 'LivingWithParents', 'OwnsHouseAndLot', 'Other', name='ownershiptypeenum'), nullable=False),
    sa.Column('ownership_type_custom', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_in_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('program_cycle', sa.Enum('SecondCycleOrEarlier', 'ThirdToFourthCycle', 'FifthToSixthCycle', 'SeventhToEighthCycle', 'NinthCycleAndBeyond', name='timeinprogramenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('years_in_program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('program_duration', sa.Enum('TwoYearsOrLess', 'ThreeToFourYears', 'FiveToSixYears', 'SixToSevenYears', 'EightYearsOrMore', name='yearsinprogramenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('years_in_program')
    op.drop_table('time_in_program')
    op.drop_table('residency')
    op.drop_table('program_benefits_received')
    op.drop_table('primary_repayment_source')
    op.drop_table('payment_history')
    op.drop_table('pastdue_ratio')
    op.drop_table('other_repayment_source')
    op.drop_table('meeting_attendance')
    op.drop_table('lending_groups')
    op.drop_table('income')
    op.drop_table('family_and_toilet_status')
    op.drop_table('expense')
    op.drop_table('co_insured')
    op.drop_table('center_status_members')
    op.drop_table('center_collection_record')
    op.drop_table('cash_flow_analysis')
    op.drop_table('beneficiaries')
    # ### end Alembic commands ###
