"""Add loan fields to client table

Revision ID: 8ac9a0894789
Revises: b251736240c5
Create Date: 2025-08-15 11:52:28.150520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac9a0894789'
down_revision = 'b251736240c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of_loan', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('loan_amount', sa.DECIMAL(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('loan_amount')
        batch_op.drop_column('type_of_loan')

    # ### end Alembic commands ###
