"""demo

Revision ID: 8bc145c210f2
Revises: 
Create Date: 2025-09-07 21:44:23.794208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc145c210f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_assessment_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('capacity_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('capacity_credit_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('residency_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('residency_credit_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('record_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('record_credit_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('center_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('center_credit_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('credit_score', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('risk_grade', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_assessment_summary')
    # ### end Alembic commands ###
