"""add status field to client

Revision ID: bdbce1de08d8
Revises: 47f6c7abff2b
Create Date: 2025-08-18 18:00:18.690050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbce1de08d8'
down_revision = '47f6c7abff2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='clientstatusenum'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
