"""submission date

Revision ID: be494671a2cc
Revises: eeb0802d4ab1
Create Date: 2025-09-04 07:59:55.980300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be494671a2cc'
down_revision = 'eeb0802d4ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        # First add the column as nullable
        batch_op.add_column(sa.Column('submission_date', sa.DateTime(), nullable=True))
    
    # Update existing rows with a default timestamp
    op.execute("UPDATE client SET submission_date = NOW() WHERE submission_date IS NULL")
    
    # Now make the column not nullable
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.alter_column('submission_date', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('submission_date')

    # ### end Alembic commands ###
