"""program benefits

Revision ID: e3ca453b46ff
Revises: 
Create Date: 2025-08-26 20:07:37.406398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e3ca453b46ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_usage_date'), ['usage_date'], unique=False)

    with op.batch_alter_table('program_benefits_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('benefits_name', sa.Enum('GYRT_LIFE_INSURANCE', 'CGL_LOAN_INSURANCE', 'BYA_MEDICAL_ASSISTANCE', 'BYA_EDUCATIONAL_ASSISTANCE', 'NONE', name='programbenefitsenum'), nullable=False))
        batch_op.drop_column('custom_description')
        batch_op.drop_column('benefits_received')
        batch_op.drop_column('score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('program_benefits_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('benefits_received', mysql.ENUM('NoBenefitsReceived', 'ReceivedOnlyOneBenefit', 'ReceivedTwoOrMoreBenefits'), nullable=False))
        batch_op.add_column(sa.Column('custom_description', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('benefits_name')

    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_usage_date'))

    op.drop_table('token_usage')
    # ### end Alembic commands ###
