"""record

Revision ID: fbe1cd3c0854
Revises: 
Create Date: 2025-09-09 18:33:15.693721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe1cd3c0854'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barangay_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('record_status', sa.Enum('SpouseOnlyKnown', 'BornAndNoRecord', 'ReputableFamily', 'RelativeInCouncil', 'FamilyElected', name='barangayrecordenum'), nullable=False),
    sa.Column('custom_description', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barangay_record')
    # ### end Alembic commands ###
